

RECAPTCHA_LANG = "en"

RECAPTCHA_PUBLIC_KEY = "6Lfz3bgUAAAAAGQ5b0nyI2u6CgDYdDy-dApv-G96"
RECAPTCHA_PRIVATE_KEY = "6Lfz3bgUAAAAAMGS_4PnlnGoy7PxCSbI6URZ8ulL"

PYTHON_RECAPTCHA_PUBLIC_KEY = "6Lfz3bgUAAAAAGQ5b0nyI2u6CgDYdDy-dApv-G96"
PYTHON_RECAPTCHA_PRIVATE_KEY = "6Lfz3bgUAAAAAMGS_4PnlnGoy7PxCSbI6URZ8ulL"


CRISPY_TEMPLATE_PACK = 'uni_form'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = '2pirinstitute@gmail.com'
EMAIL_HOST_PASSWORD = '2piRi5625'


